set tabstop=4               " number of columns occupied by a tab 
set softtabstop=4           " see multiple spaces as tabstops so <BS> does the right thing
set expandtab               " converts tabs to white space
set shiftwidth=4            " width for autoindents
set autoindent              " indent a new line the same amount as the line just typed

set number relativenumber   " add line numbers, with relative up and down indications
set cc=80                   " set an 80 column border for good coding style

filetype plugin indent on   " allow auto-indenting depending on file type
syntax on                   " syntax highlighting

set clipboard=unnamedplus   " using system clipboard
